name: .NET

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release -p:VersionPrefix=1.0.0 --version-suffix "${GITHUB_RUN_NUMBER}"
      - name: Create the package
        run: dotnet pack --configuration Release --version-suffix "${GITHUB_RUN_NUMBER}" -o src/
      - name: Publish the package to GPR
        run: dotnet nuget push src/*.nupkg --skip-duplicate -k ${{secrets.NUGET_API_KEY}}

